windows change
Signed-off-by: Xiaodong Li <xiaodong.li@intel.com>

diff --git a/.github/workflows/ci_win.yml b/.github/workflows/ci_win.yml
--- a/.github/workflows/ci_win.yml
+++ b/.github/workflows/ci_win.yml
@@ -89,11 +89,17 @@ jobs:
         shell: cmd
         run: |
           C:\7-Zip\7z.exe a c2s_obj.7z c2s.obj
-      - name: Upload Build
+          C:\7-Zip\7z.exe a c2s_build.7z c2s.src/build
+      - name: Upload Results 
         uses: actions/upload-artifact@v4
         with:
           name: SYCLomatic_Win_${{ github.sha }}
           path: c2s_obj.7z 
+      - name: Upload Results Build
+        uses: actions/upload-artifact@v4
+        with:
+          name: SYCLomatic_Win_build_${{ github.sha }}
+          path: c2s_build.7z 
 
   windows-lit:
     name: windows-lit
@@ -116,15 +122,20 @@ jobs:
           if exist c2s_obj.7z del /s /q c2s_obj.7z 
         shell: cmd
 
-      - name: Download Build
+      - name: Download Results
         uses: actions/download-artifact@v4
         with:
           name: SYCLomatic_Win_${{ github.sha }}
+      - name: Download Results Build
+        uses: actions/download-artifact@v4
+        with:
+          name: SYCLomatic_Win_build_${{ github.sha }}
 
       - name: Extract Build
         shell: cmd
         run: |
           C:\7-Zip\7z.exe x -y c2s_obj.7z
+          C:\7-Zip\7z.exe x -y c2s_build.7z
 
       - name: Process ENV
         id: process_env
@@ -142,7 +153,7 @@ jobs:
         timeout-minutes: 120
         run: |
           cd c2s.src
-          mkdir build
+          cp -rf ../build ./ 
           cd build
           cmake \
             -G Ninja \
@@ -208,78 +219,78 @@ jobs:
           rm -r tools/clang/test/dpct
           ninja check-clang-c2s -j8
      
-  windows-test:
-    name: windows-test-${{ matrix.test_suite }}-cpu
-    runs-on: win_build_sc
-    needs: [windows-build]
-    if: |
-      needs.windows-build.outputs.build_success == 'true' && github.event.pull_request.draft == false
+          #windows-test:
+          #  name: windows-test-${{ matrix.test_suite }}-cpu
+          #  runs-on: win_build_sc
+          #  needs: [windows-build]
+          #  if: |
+          #    needs.windows-build.outputs.build_success == 'true' && github.event.pull_request.draft == false
 
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - test_suite: user_guide_samples
-          - test_suite: regressions
-          - test_suite: samples
-          - test_suite: api_coverage
-          - test_suite: behavior_tests
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          path: c2s.src
+          #  strategy:
+          #    fail-fast: false
+          #    matrix:
+          #      include:
+          #        - test_suite: user_guide_samples
+          #        - test_suite: regressions
+          #        - test_suite: samples
+          #        - test_suite: api_coverage
+          #        - test_suite: behavior_tests
+          #  steps:
+          #    - uses: actions/checkout@v4
+          #      with:
+          #        path: c2s.src
 
-      - name: Checkout Test Repo
-        env:
-          FACELESS_TOKEN: ${{ secrets.GH_CI_NSTESTER_TOKEN }}
-        run: |
-          if exist test_repo rd /s /q test_repo
-          git clone https://github.com/oneapi-src/SYCLomatic-test.git test_repo -b SYCLomatic
-        shell: cmd 
+          #    - name: Checkout Test Repo
+          #      env:
+          #        FACELESS_TOKEN: ${{ secrets.GH_CI_NSTESTER_TOKEN }}
+          #      run: |
+          #        if exist test_repo rd /s /q test_repo
+          #        git clone https://github.com/oneapi-src/SYCLomatic-test.git test_repo -b SYCLomatic
+          #      shell: cmd 
 
-      - name: Cleanup Workspace
-        run: |
-          if exist c2s.obj rd /s /q c2s.obj
-          if exist c2s.src/build rd /s /q c2s.src/build
-          if exist c2s_obj.7z del /s /q c2s_obj.7z 
-        shell: cmd
-      
-      - name: Download Build
-        uses: actions/download-artifact@v4
-        with:
-          name: SYCLomatic_Win_${{ github.sha }}
+          #    - name: Cleanup Workspace
+          #      run: |
+          #        if exist c2s.obj rd /s /q c2s.obj
+          #        if exist c2s.src/build rd /s /q c2s.src/build
+          #        if exist c2s_obj.7z del /s /q c2s_obj.7z 
+          #      shell: cmd
+          #    
+          #    - name: Download Build
+          #      uses: actions/download-artifact@v4
+          #      with:
+          #        name: SYCLomatic_Win_${{ github.sha }}
 
-      - name: Extract Build
-        shell: cmd
-        run: |
-          C:\7-Zip\7z.exe x -y c2s_obj.7z
+          #    - name: Extract Build
+          #      shell: cmd
+          #      run: |
+          #        C:\7-Zip\7z.exe x -y c2s_obj.7z
 
-      - name: Process ENV
-        id: process_env
-        run: |
-          for mask_value in $(C:/jq-win64.exe -r ".[]" $GITHUB_WORKSPACE/../../../mask_env_values.json); do 
-              echo "add mask for $mask_value"; 
-              echo "::add-mask::$mask_value"; 
-          done
-        shell: bash
+          #    - name: Process ENV
+          #      id: process_env
+          #      run: |
+          #        for mask_value in $(C:/jq-win64.exe -r ".[]" $GITHUB_WORKSPACE/../../../mask_env_values.json); do 
+          #            echo "add mask for $mask_value"; 
+          #            echo "::add-mask::$mask_value"; 
+          #        done
+          #      shell: bash
 
-      - name: Prepare Env
-        timeout-minutes: 60
-        uses: ./c2s.src/devops/actions/prepare_env_win
+          #    - name: Prepare Env
+          #      timeout-minutes: 60
+          #      uses: ./c2s.src/devops/actions/prepare_env_win
 
-      - name: Run testing option_cpu
-        timeout-minutes: 600
-        shell: bash
-        run: |
-          cd test_repo
-          python run_test.py --suite ${{ matrix.test_suite }} --option option_cpu
-          echo $PWD
+          #    - name: Run testing option_cpu
+          #      timeout-minutes: 600
+          #      shell: bash
+          #      run: |
+          #        cd test_repo
+          #        python run_test.py --suite ${{ matrix.test_suite }} --option option_cpu
+          #        echo $PWD
 
-      - name: Run testing option_usmnone_cpu
-        if: success() || failure()
-        timeout-minutes: 600
-        shell: bash
-        run: |
-          cd test_repo
-          python run_test.py --suite ${{ matrix.test_suite }} --option option_usmnone_cpu
-          echo $PWD
+          #    - name: Run testing option_usmnone_cpu
+          #      if: success() || failure()
+          #      timeout-minutes: 600
+          #      shell: bash
+          #      run: |
+          #        cd test_repo
+          #        python run_test.py --suite ${{ matrix.test_suite }} --option option_usmnone_cpu
+          #        echo $PWD
